### PR TITLE
Add -isize option and XV_OPTIONS environment variable.

### PR DESCRIPTION
**Pull request by william8000**

### CODE REVIEW

**Comment by antofthy** [comment]
minor bug fix...  in NEWS.txt    and  in code   src/xv.c   around line 1740

You have   `height = width  * 4 / 3`   when height is omitted
It should   `height = width  * 3 / 4` 

That is height is supposed to be smaller than width, for a 4:3 aspect ratio  (width vs height)

**I have built this 'pull' version with the ratio fixed, and -isize works well...    GOOD JOB.**
Remember you will need to clear the ".xvpics" sub-directory and update the icons to see the change.


ASIDE:  I also set a few other minor personal adjustments such as locking the geometry position when given, and number of initial icons and reduced padding between them in the Schnauzer    But that is for me. 
(see my xv mods guide https://antofthy.gitlab.io/info/graphics/xv_mods.txt  if interested)

**Comment by william8000** [comment]
@antofthy I updated the pull request with the fixed aspect ratio.

The other changes that you suggested in xv_mods should probably be a separate pull request.
I'm neutral on them, but if the jasper people want any of them, I can make the corresponding pull request with the changes.
Should ISIZE_WPAD depend on the DPI or on ISIZE_WIDE instead of being a hard-coded value?
My -isize option uses the X library function to parse a geometry. It currently ignores the x and y if they are specified. Could the x and y be used as the padding?
Increasing MAXBRWIN from 4 to 16 probably wouldn't cause any problems.
Would increasing MAXNAMES from 4k to 64k cause any problems on systems without a lot of memory? A number of arrays are declared to MAXNAMES.
Would it be sufficient to change the xv.h to say #ifndef MAXNAMES / #define MAXNAMES 4096 / #endif so that you could control it from your build script without the need to modify the source?
The 'w' wait key is already in xvevent.c.

**Comment by mdadams** [comment]
@william8000, @antofthy:
In the future, it would be best if only the people doing releases bumped the version number in the CMakeLists.txt file.  You can still add a new entry in the NEWS.txt file but just use a dummy version+date X.Y.Z (YYYY-MM-DD) heading to be adjusted later when a release is made.

**Comment by william8000** [comment]
ok. I thought that updating the patch level was saving you work, but if it is a problem, I won't update it in the future.

**Pull request merged**
